apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prasad
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: prasad
subjects:
- kind: ServiceAccount
  name: sc
  namespace: prasad
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
